# Generated by Django 2.1.5 on 2019-01-19 02:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='photos',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
