# Generated by Django 2.1.5 on 2019-01-19 02:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcollector', '0002_human_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='hide_age',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='hide_distance',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='is_traveling',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='spotify_theme_track',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
