# Generated by Django 2.1.5 on 2019-01-19 02:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcollector', '0003_auto_20190119_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='instagram',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='t_id',
            field=models.TextField(),
        ),
    ]
