# Generated by Django 2.1.5 on 2019-01-20 20:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcollector', '0004_auto_20190119_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='spotify_top_artists',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
