# Generated by Django 2.1.5 on 2019-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcollector', '0005_human_spotify_top_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='show_gender_on_profile',
            field=models.BooleanField(null=True),
        ),
    ]
