# Generated by Django 2.1.5 on 2019-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcollector', '0006_human_show_gender_on_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='custom_gender',
            field=models.TextField(null=True),
        ),
    ]
