# Generated by Django 2.2 on 2019-04-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcollector', '0007_human_custom_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='label',
            field=models.TextField(null=True),
        ),
    ]
